feature_dim: 2
cont_dim: 2
discrete_dim: 0

hidden_size: 128
n_layers: 3
n_heads: 2

K: 200
pre_int_len: 5
post_int_len: 3
seq_range: 201
time_range: 30

batch_size: 512
lr: 1e-4
weight_decay: 1e-4
warmup_steps: 2000