feature_dim: 14
cont_dim: 14
discrete_dim: 0

hidden_size: 128
n_layers: 4
n_heads: 2

K: 17
pre_int_len: 10
post_int_len: 5
seq_range: 18
time_range: 43

batch_size: 128
lr: 1e-4
weight_decay: 1e-4
warmup_steps: 10000