feature_dim: 14
cont_dim: 14
discrete_dim: 0

hidden_size: 32
n_layers: 3
n_heads: 1

K: 16
pre_int_len: 5
post_int_len: 3
seq_range: 17
time_range: 43

batch_size: 32
lr: 1e-4
weight_decay: 1e-4
warmup_steps: 1000