feature_dim: 8
cont_dim: 8
discrete_dim: 0

hidden_size: 128
n_layers: 4
n_heads: 2

K: 16
pre_int_len: 10
post_int_len: 5
seq_range: 17
time_range: 44

batch_size: 128
lr: 1e-4
weight_decay: 1e-4
warmup_steps: 10000